
version: 2
orbs:
  android: circleci/android@1.0
jobs: 
  build:
    executor:
      name: android/android-machine
      resource-class: large
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node
      - image: appium/appium
    resource_class: large
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - android/create-avd:
          avd-name: myavd
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: myavd
          no-window: true
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline
      
      - run:
          name: Install Node
          command: |
              cd
              curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
                    sudo apt install nodejs
      - run:
          name: Print Node and NPM Version
          command: |
                    node --version
                    npm --version
      - run:
          name: Install Appium
          command: |
                    cd
                    npm install appium@1.20.2
      - run:
           name: Start Appium
           command: cd ; appium &
           background: true
      - run:
                name: Wait Until Appium Boot
                command: sleep 30
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      
     
        # run tests!
      - run: mvn clean
      - run: mvn test
    workflows:
    maven_test:
    jobs:
      - maven/test 
