
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node
      - image: circleci/android:api-29

    steps:
            - run:
                name: Install libs for libpulse
                command: |
                        cd
                        sudo apt-get update
                        sudo apt-get install pulseaudio
            - run:
                name: List Images
                command: sdkmanager --list --verbose | grep system-images
            - run:
                name: Setup Emulator
                command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo
                    "no" | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a"
            - run:
                name: Launch Emulator
                command: |
                    cd ${ANDROID_HOME}/emulator;ls
                    export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
                    emulator -avd test -skin 1440x2560 -no-window -noaudio -no-boot-anim -no-window -accel on
                background: true
            - run:
                name: Wait emulator
                command: |
                    circle-android wait-for-boot
                    adb shell input keyevent 82
            - run:
                name: Install Node
                command: |
                    cd
                    curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
                    sudo apt install nodejs
            - run:
                name: Print Node and NPM Version
                command: |
                    node --version
                    npm --version
            - run:
                name: Install Appium
                command: |
                    cd
                    npm install appium@1.14.0
            - run:
                name: Start Appium
                command: cd ; appium
                background: true
            - run:
                name: Wait Until Appium Boot
                command: sleep 30
            - checkout
            - run:
                name: Install APK
                command: adb install <Your_Application>.apk
            - run:
                name: Run Tests
                command: mvn clean test
            - store_test_results:
                path: target/surefire-reports
            - store_artifacts:
                path: target/surefire-reports
                destination: sanity-test-results
    workflows:
    maven_test:
    jobs:
      - maven/test 
